using UnityEngine;

public class Gravity
{

	/**
	 * Return the gravity force on the player generated by the obstacles
	 */
	public Vector3 GetGravity(GravityBody[] obstacles, Vector3 subjectPosition)
	{
		Vector3 gravity = Vector3.zero;

		if (obstacles != null && obstacles.Length > 0)
		{
			foreach (GravityBody body in obstacles)
			{
				Vector3 dir = body.position - subjectPosition;
				float dist = dir.magnitude;

				if (dist <= body.radiusGravity) // avoid if the player is crashed
				{
					body.Highlight(true);
					float distSurface = dist - body.radius;
					float percent = distSurface / (body.radiusGravity - body.radius);
					//float force = percent * body.mass; // mass%
					//float force = (1 / dist) * body.mass; // f(x) = 1/x * M
					float force = 667.4f * (body.mass) / Mathf.Pow(dist, 2);
					gravity += dir.normalized * force;
				} else
					body.Highlight(false);
			}
		}

		return gravity;
	}

}
