using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Gravity : MonoBehaviour
{
	public Vector3 GetGravity(ObstacleBody[] obstacles)
	{
		Vector3 gravity = Vector3.zero;

		gravity += new Vector3(0, 0.1f, 0);

		// ISSUE : the gravity vector seems to apply to the player ortho, not the global one

		// TODO : calculate the gravity generated by the obstacles

		return gravity;
	}
}
