using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Gravity : MonoBehaviour
{

	/**
	 * Return the gravity force on the player generated by the obstacles
	 */
	public Vector3 GetGravity(GravityBody[] obstacles, Vector3 subjectPosition)
	{
		Vector3 gravity = Vector3.zero;

		foreach (GravityBody body in obstacles)
		{
			Vector3 dir = body.position - subjectPosition;
			float dist = dir.magnitude;

			if (dist > body.radius)
			{
				float force = (1 / dist) * body.mass; // f(x) = 1/x * M
				gravity += dir.normalized * force;
			}
		}

		// ISSUE : the gravity near the obstacles seems to repulse the player
		// - the player velocity is not updated with the gravity effect
		//   → can be a problem? The gravity force don't reduce it with time

		return gravity;
	}
}
