using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Gravity : MonoBehaviour
{

	/**
	 * Return the gravity force on the player generated by the obstacles
	 */
	public Vector3 GetGravity(GravityBody[] obstacles, Vector3 subjectPosition)
	{
		Vector3 gravity = Vector3.zero;

		if (obstacles != null && obstacles.Length > 0)
		{
			foreach (GravityBody body in obstacles)
			{
				Vector3 dir = body.position - subjectPosition;
				float dist = dir.magnitude;

				if (dist > body.radius)
				{
					float force = (1 / dist) * body.mass; // f(x) = 1/x * M
					gravity += dir.normalized * force;
				}
			}
		}

		return gravity;
	}
}
